### ISSUE TITLE
Why I am not able to Login

### ISSUE THREAD

**Issue by david2rock** [tofzonne/instakit#3]
https://github.com/tofzonne/instakit/blob/356922ded5ec33eae1b72b702cc61913038e5f0e/main.py#L15-L16

**This is not letting me login**
it just went to the other loop
here
https://github.com/tofzonne/instakit/blob/356922ded5ec33eae1b72b702cc61913038e5f0e/main.py#L26-L34

Someone, Please help me.

**Comment by tofzonne** [comment]
Thank you David for letting me know
I will make sure of that as soon as possible.

**Comment by tofzonne** [comment]
Hey David i have fixed your issue in line 15 in this commit 18b3a433039bc3c236f847e20b7abf4ff9079c2e.
https://github.com/tofzonne/instakit/blob/18b3a433039bc3c236f847e20b7abf4ff9079c2e/main.py#L15-L24
Now you can login and enjoy instakit
Good luck 🤞
